server:
  port: 9092

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/innovacionbd
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: none
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    
    generate-ddl: false
    show-sql: true
    